import './style.css';
import {validateState} from './domain/validate.ts';
import * as A from './domain/accounting.ts';
import type {State,Invoice,Profile,VatCode} from './domain/accounting.ts';
import {parseMoney,formatMoney,percentage} from './domain/money.ts';
import {quarterForDate} from './domain/dates.ts';
import {taxScenario2026,taxSources} from './domain/tax.ts';
import {loadState,persistState,uploadDocument,download,base64ToBytes} from './services/local.ts';
import {snapshotInvoice,invoicePdf,encryptedBackup,restoreBackup,exportPackage} from './services/export.ts';
import {signIn,cloudConfigured,verifiedIdentity,connectionStatus,supabase} from './services/auth.ts';

const app=document.querySelector<HTMLDivElement>('#app')!;
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Amsterdam'}).format(new Date());
let state:State=A.emptyState(),page='overview',quarter=quarterForDate(today),error='',message='',busy=false,previewUrl='';
let ownerId='',authGeneration=0,checking=false;
const pages:Record<string,[string,string]>={overview:['Overzicht','01'],invoices:['Verkoopfacturen','02'],expenses:['Inkoop & documenten','03'],vat:['Btw & kwartaalcontrole','04'],tax:['Belasting & reserves','05'],hours:['Urenregistratie','06'],ledger:['Grootboek','07'],relations:['Relaties','08'],settings:['Instellingen & export','09']};
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(value:bigint|string)=>formatMoney(BigInt(value));
const decimal=(value:bigint|string)=>{const n=BigInt(value),a=n<0n?-n:n;return `${n<0n?'-':''}${a/100n}.${String(a%100n).padStart(2,'0')}`;};
const button=(label:string,action:string,id='',className='secondary')=>`<button class="${className}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const empty=(title:string,text:string)=>`<div class="empty"><h3>${title}</h3><p>${text}</p></div>`;
const field=(label:string,name:string,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra} required></label>`;
const select=(label:string,name:string,options:[string,string][])=>`<label>${label}<select name="${name}" required>${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></label>`;
const check=(name:string,label:string)=>`<label class="check"><input type="checkbox" name="${name}">${label}</label>`;
const form=(name:string,body:string,submit='Opslaan')=>`<form data-form="${name}">${body}<p class="form-error" role="alert"></p><div class="form-actions"><button type="submit">${submit}</button><button type="button" class="secondary" data-action="close">Annuleren</button></div></form>`;
const relationName=(i:Invoice)=>state.relations.find(r=>r.id===i.relationId)?.name??'Onbekend';
const credited=(i:Invoice)=>state.invoices.some(c=>c.creditOf===i.id);
const payable=(i:Invoice)=>i.creditOf||credited(i)?0n:A.outstanding(state,i);
function status(i:Invoice) {return i.status==='draft'?'Concept':i.creditOf?'Creditfactuur':credited(i)?'Gecrediteerd':payable(i)===0n?'Betaald':payable(i)<BigInt(i.gross)?'Deels betaald':i.due<today?'Over tijd':'Openstaand';}
const stat=(title:string,value:string,subtitle:string,target:string,accent=false)=>`<button class="stat ${accent?'accent':''}" data-action="nav" data-id="${target}"><span>${title}<b aria-hidden="true">↗</b></span><strong>${value}</strong><small>${subtitle}</small></button>`;
function invoiceTable(kind:'sale'|'purchase',limit?:number) {
 const list=state.invoices.filter(i=>i.kind===kind).slice().reverse().slice(0,limit);
 if(!list.length)return empty('Nog geen '+(kind==='sale'?'verkoopfacturen':'inkoopfacturen'),'Maak een concept om je eerste testboeking te controleren.');
 return `<div class="table-wrap"><table><thead><tr><th>Factuur / relatie</th><th>Datum</th><th>Status</th><th class="numeric">Totaal</th><th></th></tr></thead><tbody>${list.map(i=>`<tr><td><strong>${esc(i.number||'Concept')}</strong><small>${esc(relationName(i))}</small></td><td>${esc(i.date)}</td><td><span class="pill ${status(i)==='Over tijd'?'warning':''}">${status(i)}</span></td><td class="numeric">${money(i.gross)}</td><td>${button('Bekijken','invoice',i.id,'text-button')}</td></tr>`).join('')}</tbody></table></div>`;
}
function overview() {
 const report=A.vatReport(state,quarter),year=quarter.slice(0,4),revenue=-A.accountTotal(state,'8000',year),cost=A.accountTotal(state,'4400',year)+A.accountTotal(state,'4500',year),profit=revenue-cost;
 const tax=taxScenario2026(profit,false),taxLow=taxScenario2026(profit,true);const reserveTarget=tax.total+percentage(tax.total,1000n);
 const open=state.invoices.filter(i=>i.kind==='sale'&&i.status==='posted').reduce((sum,i)=>sum+payable(i),0n);
 const actions=A.alerts(state,today);const monthly=Array.from({length:12},(_,index)=>{const prefix=`${year}-${String(index+1).padStart(2,'0')}`;return state.journals.filter(j=>j.date.startsWith(prefix)).reduce((sum,j)=>sum-j.lines.filter(l=>l.account==='8000').reduce((a,l)=>a+BigInt(l.amount),0n),0n);});const maximum=monthly.reduce((a,b)=>a>b?a:b,1n);
 return `<div class="page-intro"><div><p class="eyebrow">JE ADMINISTRATIE, OP ÉÉN PLEK</p><h1>Rust in je cijfers.</h1><p>Dit staat er in je lokale testadministratie.</p></div>${button('Nieuwe factuur','new-sale','','primary')}</div>
 <div class="stats">${stat('Btw dit kwartaal',money(report.due),`${quarter} · ${money(A.reserve(state,'vat'))} gereserveerd`,'vat',true)}${stat('IB + Zvw · testscenario',year==='2026'?`${money(taxLow.total)} – ${money(tax.total)}`:'Nog geen jaarregels','Voorlopig · alleen zakelijke winst','tax')}${stat('Zakelijke winst',money(profit),`${year} · omzet minus geboekte kosten`,'ledger')}${stat('Open bij klanten',money(open),'Inclusief btw · betalingen handmatig','invoices')}</div>
 <div class="dashboard-grid"><section class="panel"><div class="section-head"><div><p class="eyebrow">JAAROVERZICHT ${year}</p><h2>Wat er binnenkomt</h2></div><span class="pill">Geboekte testgegevens</span></div><div class="revenue-total"><strong>${money(revenue)}</strong><span>omzet exclusief btw</span></div><div class="bars" aria-label="Omzet per maand">${monthly.map((n,index)=>`<div class="bar-item"><div class="bar-space"><div class="bar" style="height:${n>0n?Math.max(3,Number(n*100n/maximum)):0}%" title="${money(n)}"></div></div><span>${['jan','feb','mrt','apr','mei','jun','jul','aug','sep','okt','nov','dec'][index]}</span></div>`).join('')}</div><div class="summary-row"><span>Kosten <strong>${money(cost)}</strong></span><span>Na testreserve IB <strong>${year==='2026'?money(profit-reserveTarget):'—'}</strong></span></div><p class="muted">Dit is geen saldo van je persoonlijke bankrekening. Onvolledige invoer maakt het overzicht onvolledig.</p></section>
 <section class="panel action-panel"><p class="eyebrow">AANDACHT NODIG</p><h2>Je volgende stappen <span class="count">${actions.length}</span></h2>${actions.length?actions.slice(0,5).map(a=>`<button class="action-row" data-action="nav" data-id="${a.target}"><span class="dot"></span><span>${esc(a.title)}</span><b>→</b></button>`).join(''):empty('Alles in deze test is bijgewerkt','Controleer wel of alle documenten zijn toegevoegd.')}<div class="deadline"><strong>Btw-controle ${quarter}</strong><p>Controleer de aangiftedeadline in Mijn Belastingdienst Zakelijk. Afsluiten gebeurt uitsluitend na jouw controle.</p>${button('Naar kwartaalcontrole','nav','vat','text-button')}</div></section></div>
 <section class="panel"><div class="section-head"><div><p class="eyebrow">RECENT</p><h2>Verkoopfacturen</h2></div>${button('Alle facturen →','nav','invoices','text-button')}</div>${invoiceTable('sale',5)}</section>`;
}
function expenses() {return `<div class="section-head"><div><h1>Inkoop & documenten</h1><p>Voeg een origineel toe en controleer de boeking.</p></div>${button('Nieuw kostenconcept','new-purchase','','primary')}</div><section class="panel"><label class="upload">＋ PDF of foto toevoegen<input id="upload" type="file" accept="application/pdf,image/jpeg,image/png,image/heic"></label><p class="muted">Alleen testdocumenten. Maximaal 10 MB. Tekst-pdf’s geven een veldvoorstel. Foto’s en scans verwerk je voorlopig handmatig.</p><div class="document-list">${state.documents.map(d=>`<div class="document-row"><div><strong>${esc(d.name)}</strong><small>Origineel bewaard · SHA-256 ${d.sha256.slice(0,12)}…</small></div>${button('Openen','document',d.id)}${button('Herkenning','ocr',d.id)}</div>`).join('')}</div></section><section class="panel">${invoiceTable('purchase')}</section><section class="panel"><div class="section-head"><h2>Abonnementen</h2>${button('Toevoegen','new-subscription')}</div>${state.subscriptions.length?state.subscriptions.map(s=>`<div class="list-row"><div><strong>${esc(s.name)}</strong><small>${s.businessBps/100}% zakelijk · verwacht per maand</small></div><strong>${money(s.monthly)}</strong></div>`).join(''):empty('Geen abonnementen','Leg verwachte facturen vast om ontbrekende maanden te signaleren.')}</section>`;}
function vatPage() {const r=A.vatReport(state,quarter),p=state.periods.find(p=>p.id===quarter);return `<div class="section-head"><div><h1>Btw & kwartaalcontrole</h1><p>Van aangiftevak naar iedere bronboeking.</p></div><span class="pill">${p?.status==='closed'?'Afgesloten':'Open · onvolledig tot controle'}</span></div><section class="panel"><div class="section-head"><h2>${quarter}</h2>${button('Kwartaalpakket downloaden','export')}</div><div class="table-wrap"><table><thead><tr><th>Vak</th><th>Beschrijving</th><th>Grondslag</th><th>Btw in centen nauwkeurig</th></tr></thead><tbody>${Object.entries(r.boxes).map(([box,value])=>`<tr><td><strong>${box}</strong></td><td>${{'1a':'Nederlandse omzet 21%','4a':'Diensten buiten EU · verlegd','4b':'Diensten binnen EU · verlegd','5b':'Voorbelasting'}[box]}</td><td>${money(value.base)}</td><td>${money(value.tax)}</td></tr>`).join('')}</tbody></table></div><div class="total-row">Exact saldo <strong>${money(r.due)}</strong></div><div class="total-row">Na afronding per vak <strong>${money(r.roundedDue)}</strong></div><p class="notice">Dit testoverzicht dient geen aangifte in. Controleer de fiscale verwerking en afronding in hele euro’s vóór overname.</p></section><section class="panel"><h2>Kwartaal afsluiten</h2>${p?.status==='closed'?`<p>Handmatig ingediend: ${esc(p.submittedAt)} · aangegeven ${money(p.declared)}</p><p>Betaald: ${esc(p.paidAt||'Nog niet geregistreerd')}</p>${!p.paidAt?button('Btw betaald registreren','vat-paid'):''}<p class="muted">Een later document in deze periode wordt geblokkeerd voor definitief boeken. Een correctie vraagt eerst fiscale beoordeling.</p>`:`<form data-form="close-period">${A.closingChecks.map((c,i)=>check('check'+i,esc(c))).join('')}<div class="form-grid">${field('Datum handmatig ingediend','date',today,'date')}${field('Werkelijk aangegeven bedrag (€)','declared',String(r.roundedDue/100n),'text','inputmode="decimal"')}</div>${check('confirmed','Ik heb het kwartaal gecontroleerd en wil het in deze test sluiten.')}<p class="form-error" role="alert"></p><button>Afsluiten na controle</button></form>`}</section><section class="panel"><h2>Onderliggende boekingen</h2>${journalRows(r.entries)}</section>`;}
function taxPage() {const profit=-A.accountTotal(state,'8000','2026')-A.accountTotal(state,'4400','2026')-A.accountTotal(state,'4500','2026'),one=taxScenario2026(profit,true),two=taxScenario2026(profit,false);return `<h1>Belasting & reserves</h1><p>Een uitlegbaar zakelijk testscenario voor 2026.</p><p class="notice"><strong>Voorlopig, geen persoonlijke aangifte.</strong> Aannames: onder AOW-leeftijd, heel jaar Nederlands verzekerd, alleen deze zakelijke winst, geen ander inkomen of privéaftrek. Geen urenafhankelijke aftrek in 2026. Deze fiscale versie is niet vrijgegeven voor productie.</p><div class="two-col">${[one,two].map((t,index)=>`<section class="panel"><p class="eyebrow">SCENARIO ${index+1}</p><h2>${index===0?'Ondernemer voor IB':'Inkomsten uit overig werk'}</h2><dl>${[['Geboekte winst',t.profit],['Mkb-winstvrijstelling',t.exemption],['Belastbaar',t.taxable],['Belasting vóór kortingen',t.gross+t.limitation],['Algemene heffingskorting',t.general],['Arbeidskorting',t.labour],['IB na kortingen',t.incomeTax],['Bijdrage Zvw',t.zvw],['Totaal testscenario',t.total]].map(([l,v])=>`<div><dt>${l}</dt><dd>${money(v as bigint)}</dd></div>`).join('')}</dl></section>`).join('')}</div><section class="panel"><div class="section-head"><h2>Werkelijk gereserveerd</h2>${button('Reserve bijwerken','new-reserve')}</div><div class="two-col"><p>Btw <strong>${money(A.reserve(state,'vat'))}</strong></p><p>Inkomstenbelasting <strong>${money(A.reserve(state,'income'))}</strong></p></div><p>Rekenbuffer voor dit scenario: ${money(two.total+percentage(two.total,1000n))} (hoogste scenario + 10%). Verschil met reserve: ${money(two.total+percentage(two.total,1000n)-A.reserve(state,'income'))}.</p><p class="muted">Deze buffer is een testaanname en geen garantie bij overig inkomen of fiscale afwijkingen.</p><details><summary>Reservehistorie</summary>${state.reserves.map(r=>`<p>${r.date} · ${r.type==='vat'?'Btw':'IB'} · ${money(r.amount)}</p>`).join('')}</details><details><summary>Bronnen en rekenversie 2026-sandbox-v1</summary>${Object.entries(taxSources).map(([name,url])=>`<p><a href="${url}" target="_blank" rel="noopener noreferrer">${name} · Belastingdienst</a></p>`).join('')}</details></section>`;}
function journalRows(entries:A.Journal[]) {return entries.length?entries.slice().reverse().map(j=>`<details class="journal"><summary><span>${j.date} · ${esc(j.description)}</span><small>${j.lines.length} regels · in balans</small></summary><div class="table-wrap"><table><thead><tr><th>Rekening</th><th>Debet</th><th>Credit</th></tr></thead><tbody>${j.lines.map(l=>`<tr><td>${l.account} · ${A.accounts[l.account]}</td><td>${BigInt(l.amount)>0n?money(l.amount):'—'}</td><td>${BigInt(l.amount)<0n?money(-BigInt(l.amount)):'—'}</td></tr>`).join('')}</tbody></table></div>${state.invoices.some(i=>i.id===j.sourceId)?button('Naar factuur / bron','invoice',j.sourceId):''}</details>`).join(''):empty('Nog geen boekingen','Definitief goedgekeurde testfacturen verschijnen hier.');}
function ledger() {return `<h1>Grootboek</h1><p>Iedere definitieve testboeking is gebalanceerd en herleidbaar.</p><section class="panel"><h2>Saldi ${quarter.slice(0,4)}</h2><div class="account-grid">${Object.entries(A.accounts).map(([code,name])=>`<div class="list-row"><span>${code} · ${name}</span><strong>${money(A.accountTotal(state,code as A.Account,quarter.slice(0,4)))}</strong></div>`).join('')}</div></section><section class="panel"><h2>Journaalposten</h2>${journalRows(state.journals)}</section>`;}
function hoursPage() {const proven=state.hours.filter(h=>h.date.startsWith('2027')&&h.evidence==='proven').reduce((a,h)=>a+h.minutes,0);return `<div class="section-head"><div><h1>Urenregistratie</h1><p>Bewijsbare bedrijfsuren vanaf 1 januari 2027.</p></div>${button('Uren toevoegen','new-hours','','primary')}</div><section class="panel"><p class="eyebrow">URENCRITERIUM · PLANNING 2027</p><h2>${Math.floor(proven/60)} uur ${proven%60} minuten onderbouwd</h2><progress max="73500" value="${proven}"></progress><p class="muted">Streefwaarde 1.225 uur uit de huidige baseline; bevestig de regels voor 2027. Onzekere en gereconstrueerde uren tellen niet standaard mee. Geen automatische aftrek.</p></section><section class="panel">${state.hours.length?state.hours.slice().reverse().map(h=>`<div class="list-row"><div><strong>${esc(h.description)}</strong><small>${h.date} · ${esc(h.project)} · ${h.billable?'Declarabel':'Bedrijfsuren'} · ${esc(h.evidence)}</small></div><strong>${Math.floor(h.minutes/60)}:${String(h.minutes%60).padStart(2,'0')}</strong></div>`).join(''):empty('Nog geen uren','Voeg administratie, projecten en andere aantoonbare bedrijfsuren toe.')}</section>`;}
function relationsPage() {return `<div class="section-head"><h1>Klanten & leveranciers</h1>${button('Relatie toevoegen','new-relation','','primary')}</div><section class="panel">${state.relations.length?state.relations.map(r=>`<div class="list-row"><div><strong>${esc(r.name)}</strong><small>${esc(r.address)} · ${esc(r.email)}</small></div><span class="pill">${r.kind==='customer'?'Klant':'Leverancier'} · ${r.country}</span></div>`).join(''):empty('Nog geen relaties','Voeg een fictieve klant of leverancier toe voor de lokale test.')}</section>`;}
function settings() {return `<h1>Instellingen & export</h1><p>Controle over je gegevens, koppelingen en herstel.</p><div class="two-col"><section class="panel"><div class="section-head"><h2>Bedrijfsprofiel</h2>${button('Bewerken','profile')}</div><p><strong>${esc(state.profile.name||'Nog niet ingevuld')}</strong></p><p>${esc(state.profile.address)}</p><p>Alleen testgegevens in deze lokale omgeving.</p></section><section class="panel"><h2>Online omgeving</h2><p>${cloudConfigured?'Google-account en actieve eigenaarstoegang gecontroleerd.':'Google-login, Supabase en mail zijn nog niet aangesloten.'}</p>${button('Verbinding controleren','connection')}${button('Google-toegang controleren','identity')}${button('Inloggen met Google','login')}<p class="muted">De lokale testmodus geeft geen toegang tot cloudgegevens.</p></section></div><section class="panel"><h2>Export & versleutelde back-up</h2><p>Een export bevat leesbare CSV’s, JSON, originele documenten, factuur-pdf’s en hashmanifest. Een back-up is versleuteld met jouw wachtzin.</p><div class="toolbar">${button('Kwartaalpakket (ZIP)','export')}${button('Versleutelde back-up','backup')}${button('Back-up herstellen','restore')}</div><p class="muted">Bewaar de wachtzin apart. Herstellen vervangt de huidige lokale testadministratie na extra bevestiging. Dit is nog geen geplande off-siteback-updienst.</p></section><section class="panel"><div class="section-head"><h2>Verwerking & controles</h2>${button('Controle uitvoeren','reconcile')}</div>${state.jobs.length?state.jobs.slice().reverse().map(j=>`<div class="list-row"><div><strong>${esc(j.kind)}</strong><small>${esc(j.reason)}</small></div><span class="pill">${j.status}</span></div>`).join(''):empty('Geen verwerkingstaken','Uploads en verzendverzoeken blijven traceerbaar in de wachtrij.')}</section><section class="panel"><h2>Wijzigingshistorie</h2>${state.audit.slice(-25).reverse().map(a=>`<div class="list-row"><div><strong>${esc(a.action)}</strong><small>${esc(a.at)} · ${esc(a.detail)}</small></div></div>`).join('')}</section>`;}
function render() {
 if(!ownerId){renderLogin();return;}
 app.innerHTML=`<a class="skip" href="#main">Naar inhoud</a><div class="shell"><aside class="sidebar"><a class="brand" href="#overview"><span>↗</span><div>ZZP<small>BOEKHOUDING</small></div></a><nav aria-label="Hoofdnavigatie">${Object.entries(pages).map(([id,[label,num]])=>`<button data-action="nav" data-id="${id}" ${page===id?'aria-current="page"':''}><span>${num}</span>${label}</button>`).join('')}</nav><div class="sidebar-bottom"><span class="avatar">Z</span><div>Jouw onderneming<small>Lokale testadministratie</small></div></div></aside><div class="workspace"><header><span>${pages[page]?.[0]??'Overzicht'}</span><div>${button('Uitloggen','logout','','text-button')}<span class="status-dot"></span> Lokaal opgeslagen <label class="quarter"><span class="sr-only">Kwartaal</span><select id="quarter">${['2026-Q2','2026-Q3','2026-Q4','2027-Q1'].map(q=>`<option ${q===quarter?'selected':''}>${q}</option>`).join('')}</select></label></div></header><div class="sandbox-banner"><strong>Testomgeving</strong><span>Alleen fictieve gegevens. Testgegevens staan in deze browser en synchroniseren nog niet met Supabase. Externe verzending staat uit.</span></div><main id="main">${error?`<p class="error-banner" role="alert">${esc(error)}</p>`:''}${message?`<p class="success-banner" role="status">${esc(message)}</p>`:''}${page==='overview'?overview():page==='invoices'?`<div class="section-head"><div><h1>Verkoopfacturen</h1><p>Van concept tot betaling, met jouw controle.</p></div><div class="toolbar">${button('Bestaande factuur importeren','import-sale')}${button('Nieuwe factuur','new-sale','','primary')}</div></div><section class="panel">${invoiceTable('sale')}</section>`:page==='expenses'?expenses():page==='vat'?vatPage():page==='tax'?taxPage():page==='hours'?hoursPage():page==='ledger'?ledger():page==='relations'?relationsPage():settings()}</main><footer>ZZP Boekhouding Template · Alle bedragen in EUR <span>Testgegevens · geen officiële administratie</span></footer></div></div><dialog id="dialog"><div id="dialog-content"></div></dialog>`;
}
function dialog(title:string,content:string) {document.getElementById('dialog-content')!.innerHTML=`<div class="section-head"><h2>${title}</h2>${button('Sluiten','close','','text-button')}</div>${content}`;document.querySelector<HTMLDialogElement>('#dialog')!.showModal();}
function closeDialog() {document.querySelector<HTMLDialogElement>('#dialog')!.close();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}}
async function mutate(fn:(s:State)=>void|Promise<unknown>,success='Opgeslagen in de lokale testadministratie.') {if(busy||!ownerId)return;busy=true;const generation=authGeneration,account=ownerId;const copy=structuredClone(state);try{const identity=await verifiedIdentity();if(!identity||identity.id!==account){lock();return;}await fn(copy);validateState(copy);if(generation!==authGeneration||ownerId!==account)return;await persistState(copy,state.revision,account);if(generation!==authGeneration)return;state=copy;error='';message=success;closeDialog();render();}catch(e){const text=e instanceof Error?e.message:'Er ging iets mis.';const target=document.querySelector<HTMLDialogElement>('dialog')?.open?document.querySelector('.form-error'):null;if(target)target.textContent=text;else{error=text;render();}}finally{busy=false;}}
function newInvoice(kind:'sale'|'purchase',editId='',documentId='',importing=false) {const relations=state.relations.filter(r=>r.kind===(kind==='sale'?'customer':'supplier'));if(!relations.length){dialog('Eerst een relatie toevoegen','<p>Voeg eerst een '+(kind==='sale'?'klant':'leverancier')+' toe.</p>'+button('Relatie toevoegen','new-relation'));return;}dialog(importing?'Bestaande factuur importeren':editId?'Concept aanpassen':kind==='sale'?'Nieuwe verkoopfactuur':'Nieuw kostenconcept',form(importing?'import-sale':'invoice',`<input type="hidden" name="editId" value="${editId}"><input type="hidden" name="kind" value="${kind}">${importing?field('Bestaand factuurnummer','importNumber')+select('Originele factuur-pdf','importDocument',state.documents.filter(d=>d.type==='application/pdf').map(d=>[d.id,d.name]))+'<label>Betaaldatum (leeg indien onbetaald)<input name="paidDate" type="date"></label>':''}${select(kind==='sale'?'Klant':'Leverancier','relationId',relations.map(r=>[r.id,r.name]))}${field('Omschrijving','description','','text','maxlength="300"')}<div class="form-grid">${field('Factuurdatum','date',today,'date')}${field('Prestatiedatum','serviceDate',today,'date')}${field('Bedrag exclusief btw (€)','net','','text','inputmode="decimal"')}${kind==='purchase'?field('Btw volgens origineel (€)','vat','0,00','text','inputmode="decimal"')+field('Totaal volgens origineel (€)','gross','','text','inputmode="decimal"'):''}</div>${select('Btw-behandeling','vatCode',kind==='sale'?[['NL21','Nederland · 21%']]:[['NL21','Nederland · 21%'],['NONE','Geen aftrekbare btw'],['EU_SERVICE','EU-dienst · verlegd 21%'],['NON_EU_SERVICE','Niet-EU-dienst · verlegd 21%']])}${kind==='purchase'?`${select('Origineel document','documentId',state.documents.map(d=>[d.id,d.name]))}${field('Factuurnummer leverancier','supplierNumber')}${select('Kostencategorie','costAccount',[['4400','Softwarekosten'],['4500','Overige zakelijke kosten']])}<div class="form-grid">${field('Zakelijk gebruik (%)','business','100','number','min="0" max="100"')}${field('Btw-aftrek zakelijk deel (%)','deduction','100','number','min="0" max="100"')}</div>${field('Onderbouwing gebruik en btw-behandeling','reason')}`:''}${importing?check('confirmed','Ik heb de bestaande factuur en eventuele betaaldatum gecontroleerd.'):''}`, importing?'Bestaande testfactuur importeren':'Concept opslaan'));
 const f=document.querySelector<HTMLFormElement>('dialog form')!;const existing=state.invoices.find(i=>i.id===editId);if(existing){for(const [k,v]of Object.entries({...existing,net:decimal(existing.net),vat:decimal(existing.vat),gross:decimal(existing.gross),business:existing.businessBps/100,deduction:existing.deductionBps/100})){const el=f.elements.namedItem(k) as HTMLInputElement|null;if(el)el.value=String(v);}}
 if(documentId){(f.elements.namedItem('documentId') as HTMLSelectElement).value=documentId;const doc=state.documents.find(d=>d.id===documentId)!;if(doc.proposal){for(const [k,field] of Object.entries(doc.proposal.fields)){const el=f.elements.namedItem(k) as HTMLInputElement|null;if(el)el.value=field.value;}const note=document.createElement('p');note.className='notice';note.textContent='Voorstel uit tekstherkenning; betrouwbaarheid is niet gevalideerd. Controleer alle velden en het origineel.';f.prepend(note);}}
}
async function invoiceDetail(id:string) {const i=state.invoices.find(i=>i.id===id)!;dialog(`${i.number||'Concept'} · ${esc(relationName(i))}`,`<p>${esc(i.description)}</p><p>${i.date} · prestatie ${i.serviceDate} · vervalt ${i.due}</p><dl><div><dt>Exclusief btw</dt><dd>${money(i.net)}</dd></div><div><dt>Btw · ${i.vatCode}</dt><dd>${money(i.vat)}</dd></div><div><dt>Totaal</dt><dd>${money(i.gross)}</dd></div><div><dt>Openstaand</dt><dd>${money(payable(i))}</dd></div></dl>${i.kind==='purchase'?`<p>${i.businessBps/100}% zakelijk · ${i.deductionBps/100}% btw-aftrek op zakelijk deel</p><p>${esc(i.reason)}</p>${button('Origineel bekijken','document',i.documentId)}${i.status==='posted'?`<p>Huidige kostenverdeling: ${Object.entries(A.costBalances(state,i.id)).filter(([,v])=>v!==0n).map(([k,v])=>`${esc(A.accounts[k as A.Account])}: ${money(v)}`).join(' · ')}</p>${button('Categorie corrigeren','reclassify',i.id)}`:''}`:''}${i.status==='draft'?button('Concept aanpassen','edit-invoice',i.id)+button('Concept intrekken','discard',i.id)+form('approve',`<input type="hidden" name="id" value="${i.id}">${check('confirmed','Ik heb omschrijving, relatie, bedragen, data en btw-behandeling gecontroleerd. Alleen in deze testadministratie definitief boeken.')}`,'Gecontroleerd boeken'):`<p><span class="pill">${status(i)}</span></p><div class="toolbar">${i.kind==='sale'?button('Testfactuur PDF','pdf',id):''}${payable(i)>0n?button('Betaling registreren','payment',id):''}${i.kind==='sale'&&!i.creditOf?button('Verzendverzoek','send',id)+button('Herinneringsconcept','reminder',id)+button('Creditfactuur','credit',id):''}</div>`}`);}
app.addEventListener('click',async event=>{const element=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!element)return;const action=element.dataset.action,id=element.dataset.id??'';try{
 if(action==='login'){await signIn();return;}
 if(action==='retry-auth'){await start();return;}
 if(action==='logout'){lock();await supabase?.auth.signOut();return;}
 if(!ownerId)return;
 if(action==='nav'){page=id;error='';message='';render();location.hash=id;return;}
 if(action==='close'){closeDialog();return;}
 if(action==='new-sale'||action==='new-purchase'){newInvoice(action==='new-sale'?'sale':'purchase');return;}
 if(action==='import-sale'){newInvoice('sale','','',true);return;}
 if(action==='edit-invoice'){const i=state.invoices.find(i=>i.id===id)!;newInvoice(i.kind,id);return;}
 if(action==='discard'){dialog('Concept intrekken',form('discard',`<input type="hidden" name="id" value="${id}">`+field('Reden','reason'),'Concept intrekken'));return;}
 if(action==='proposal-draft'){newInvoice('purchase','',id);return;}
 if(action==='invoice'){await invoiceDetail(id);return;}
 if(action==='profile'){dialog('Bedrijfsgegevens voor de test',form('profile',Object.entries({name:'Handelsnaam',legalName:'Juridische naam',address:'Volledig adres',kvk:'KVK-nummer',vatId:'Btw-id',iban:'IBAN',email:'E-mailadres'}).map(([key,label])=>field(label,key,state.profile[key as keyof Profile])).join('')));return;}
 if(action==='new-relation'){dialog('Klant of leverancier toevoegen',form('relation',select('Type','kind',[['customer','Nederlandse klant'],['supplier','Leverancier']])+field('Naam','name')+field('Adres','address')+field('E-mailadres','email','','email')+select('Land','country',[['NL','Nederland'],['IE','Ierland'],['US','Verenigde Staten'],['DE','Duitsland'],['GB','Verenigd Koninkrijk']])+field('Betalingstermijn (dagen)','term','14','number','min="0" max="365"')));return;}
 if(action==='new-reserve'){dialog('Reserve bijwerken',form('reserve',select('Belasting','type',[['vat','Btw'],['income','Inkomstenbelasting']])+field('Werkelijk gereserveerd (€)','amount','0,00','text','inputmode="decimal"')+field('Bijgewerkt op','date',today,'date')));return;}
 if(action==='new-subscription'){dialog('Abonnement toevoegen',form('subscription',select('Leverancier','relationId',state.relations.filter(r=>r.kind==='supplier').map(r=>[r.id,r.name]))+field('Naam abonnement','name')+field('Verwacht maandbedrag inclusief btw (€)','monthly')+field('Zakelijk percentage','business','100','number','min="0" max="100"')));return;}
 if(action==='new-hours'){dialog('Bedrijfsuren toevoegen',form('hours',field('Datum','date',today<'2027-01-01'?'2027-01-01':today,'date')+field('Duur in minuten','minutes','60','number','min="1" max="1440"')+field('Activiteit','description')+field('Project / opdrachtgever','project')+select('Bewijsstatus','evidence',[['proven','Onderbouwd'],['reconstructed','Achteraf gereconstrueerd'],['uncertain','Onzeker']])+field('Bewijsverwijzing / toelichting','reference')+check('billable','Declarabele uren')));return;}
 if(action==='payment'){const i=state.invoices.find(i=>i.id===id)!;dialog('Betaling via privérekening',form('payment',`<input type="hidden" name="id" value="${id}"><input type="hidden" name="key" value="${A.uid()}">`+field('Betaaldatum','date',today,'date')+field('Ontvangen / betaald bedrag (€)','amount',decimal(payable(i)))+check('confirmed','Ik heb deze betaling gecontroleerd.')));return;}
 if(action==='credit'){dialog('Correctie via creditfactuur',form('credit',`<input type="hidden" name="id" value="${id}">`+field('Creditdatum','date',today,'date')+field('Reden van correctie','reason')+check('confirmed','Ik bevestig deze volledige creditboeking.')));return;}
 if(action==='document'){const d=state.documents.find(d=>d.id===id);if(!d)throw new Error('Document niet gevonden.');if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(new Blob([base64ToBytes(d.base64) as BlobPart],{type:d.type}));dialog(esc(d.name),`${d.type==='application/pdf'?`<iframe title="Origineel testdocument" src="${previewUrl}"></iframe>`:d.type==='image/heic'?'<p>HEIC-preview niet ondersteund. Download het origineel.</p>':`<img class="document-preview" alt="Origineel testdocument" src="${previewUrl}">`}<a class="download-link" href="${previewUrl}" download="${esc(d.name)}">Origineel downloaden</a><p class="hash">SHA-256 ${d.sha256}</p>`);return;}
 if(action==='pdf'){const i=state.invoices.find(i=>i.id===id)!;download(await invoicePdf(state,i),`TEST-${i.number}.pdf`,'application/pdf');return;}
 if(action==='ocr'){const doc=state.documents.find(d=>d.id===id)!;if(doc.type!=='application/pdf'){await mutate(s=>{A.enqueue(s,'extract',id);});return;}element.disabled=true;try{const {extractPdf}=await import('./services/extract.ts');const proposal=await extractPdf(doc);await mutate(s=>{const d=s.documents.find(d=>d.id===id)!;d.proposal=proposal;d.extraction='review';A.audit(s,'extraction_proposed',id,proposal.engine);},'Pdf-tekst lokaal herkend; controle verplicht.');dialog('Herkenningsvoorstel',`<p>Dit zijn voorstellen, geen boeking. Bekijk het originele document voordat je ze gebruikt.</p><dl>${Object.entries(proposal.fields).map(([name,f])=>`<div><dt>${esc({net:'Exclusief btw',vat:'Btw',gross:'Totaal',date:'Factuurdatum',supplierNumber:'Factuurnummer'}[name]||name)}</dt><dd>${esc(f.value)}<small>Bron: ${esc(f.source)} · handmatig controleren</small></dd></div>`).join('')}</dl><p>${proposal.warnings.map(esc).join('<br>')}</p>${button('Origineel bekijken','document',id)}${button('Gebruik als kostenconcept','proposal-draft',id)}`);}finally{element.disabled=false;}return;}
 if(action==='send'||action==='reminder'){await mutate(s=>{A.enqueue(s,action,id);},'Verzoek geregistreerd. De externe koppeling is uitgeschakeld; er is niets verstuurd.');return;}
 if(action==='export'){download(await exportPackage(state,quarter),`zzp-boekhouding-TEST-${quarter}.zip`,'application/zip');message='Kwartaalpakket gedownload. Controleer het pakket voordat je het kwartaal afsluit.';render();return;}
 if(action==='backup'){dialog('Versleutelde testback-up',form('backup',field('Wachtzin (minimaal 12 tekens)','password','','password','minlength="12" autocomplete="new-password"')+field('Herhaal wachtzin','repeat','','password','minlength="12" autocomplete="new-password"'),'Back-up downloaden'));return;}
 if(action==='restore'){dialog('Lokale testback-up herstellen',form('restore','<label>Back-upbestand<input name="backup" type="file" required></label>'+field('Wachtzin','password','','password','minlength="12"')+check('confirmed','Ik wil de huidige lokale testadministratie vervangen door deze back-up.'),'Controleren en herstellen'));return;}
 if(action==='reconcile'){const count=A.alerts(state,today).length;message=`Controle uitgevoerd: ${count} actiepunten. Er zijn geen boekingen gewijzigd.`;render();return;}
 if(action==='vat-paid'){dialog('Btw-betaling registreren',form('vat-paid',field('Werkelijke betaaldatum','date',today,'date')+check('confirmed','Ik heb de betaling gecontroleerd.')));return;}
 if(action==='reclassify'){dialog('Kostencategorie corrigeren',form('reclassify',`<input type="hidden" name="id" value="${id}"><input type="hidden" name="key" value="${A.uid()}"><p>Dit maakt een aparte correctieboeking. Controleer de categorie en datum.</p>${select('Nieuwe categorie','costAccount',[['4400','Softwarekosten'],['4500','Overige zakelijke kosten']])}${field('Correctiedatum','date',today,'date')}${field('Reden','reason')}${check('confirmed','Ik heb deze categoriecorrectie gecontroleerd.')}`,'Correctie boeken'));return;}
 if(action==='identity'){const user=await verifiedIdentity();if(!user){lock();return;}message=user?'Google-account en eigenaarstoegang geverifieerd. De administratie blijft voorlopig een lokale testadministratie.':'Nog niet ingelogd met Google.';error='';render();return;}
 if(action==='connection'){element.disabled=true;try{message=await connectionStatus();error='';render();}finally{element.disabled=false;}return;}
 if(action==='login'){await signIn();return;}
 }catch(e){error=e instanceof Error?e.message:'De actie is mislukt.';render();}});
app.addEventListener('change',async event=>{if(!ownerId)return;const target=event.target as HTMLInputElement;if(target.id==='quarter'){quarter=target.value;render();}if(target.id==='upload'&&target.files?.[0]){const file=target.files[0];await mutate(async s=>{await uploadDocument(s,file);},'Origineel testdocument toegevoegd. Controleer de velden handmatig.');}});
app.addEventListener('submit',async event=>{event.preventDefault();if(!ownerId)return;const target=event.target as HTMLFormElement;const data=new FormData(target),get=(name:string)=>String(data.get(name)??''),confirmed=data.has('confirmed');const type=target.dataset.form;
 await mutate(async s=>{
 if(type==='profile')A.saveProfile(s,Object.fromEntries(['name','legalName','address','kvk','vatId','iban','email'].map(k=>[k,get(k)])) as Profile);
 if(type==='relation')A.addRelation(s,{name:get('name'),address:get('address'),email:get('email'),kind:get('kind') as 'customer'|'supplier',country:get('country'),term:Number(get('term'))});
 if(type==='reclassify')A.reclassifyCost(s,get('id'),get('costAccount') as '4400'|'4500',get('date'),get('reason'),get('key'),confirmed);
 if(type==='discard')A.discardDraft(s,get('id'),get('reason'));
 if(type==='invoice'||type==='import-sale'){const input={kind:get('kind') as 'sale'|'purchase',relationId:get('relationId'),description:get('description'),date:get('date'),serviceDate:get('serviceDate'),net:String(parseMoney(get('net'))),vat:get('vat')?String(parseMoney(get('vat'))):'0',expectedGross:get('gross')?String(parseMoney(get('gross'))):undefined,vatCode:get('vatCode') as VatCode,businessBps:get('business')?Number(get('business'))*100:10000,deductionBps:get('deduction')?Number(get('deduction'))*100:10000,costAccount:(get('costAccount')||undefined) as '4400'|'4500'|undefined,reason:get('reason'),supplierNumber:get('supplierNumber'),documentId:type==='import-sale'?get('importDocument'):get('documentId')};if(type==='import-sale')A.importExistingSale(s,input,get('importNumber'),get('paidDate')||undefined,confirmed);else if(get('editId'))A.updateDraft(s,get('editId'),input);else A.createDraft(s,input);}
 if(type==='approve'){const i=A.approveInvoice(s,get('id'),confirmed);if(i.kind==='sale')await snapshotInvoice(s,i);}
 if(type==='payment'){if(!confirmed)throw new Error('Bevestig de gecontroleerde betaling.');A.recordPayment(s,get('id'),get('date'),String(parseMoney(get('amount'))),get('key'));}
 if(type==='credit'){if(!confirmed)throw new Error('Bevestig de correctie.');const i=A.reverseInvoice(s,get('id'),get('date'),get('reason'));await snapshotInvoice(s,i);}
 if(type==='reserve')A.setReserve(s,get('type') as 'vat'|'income',String(parseMoney(get('amount'))),get('date'));
 if(type==='subscription'){const monthly=parseMoney(get('monthly'));if(monthly<0n)throw new Error('Bedrag mag niet negatief zijn.');s.subscriptions.push({id:A.uid(),name:get('name'),relationId:get('relationId'),monthly:String(monthly),businessBps:Number(get('business'))*100,active:true});A.audit(s,'subscription_created','subscription',get('name'));}
 if(type==='hours')A.addHours(s,{date:get('date'),minutes:Number(get('minutes')),description:get('description'),project:get('project'),billable:data.has('billable'),evidence:get('evidence') as A.Hours['evidence'],reference:get('reference')});
 if(type==='close-period'){if(!confirmed)throw new Error('Bevestig de afsluiting.');A.closePeriod(s,quarter,get('date'),String(parseMoney(get('declared'))),A.closingChecks.filter((_,i)=>data.has('check'+i)));}
 if(type==='vat-paid'){if(!confirmed)throw new Error('Bevestig de betaling.');s.periods.find(p=>p.id===quarter)!.paidAt=get('date');A.audit(s,'vat_paid',quarter,get('date'));}
 if(type==='backup'){if(get('password')!==get('repeat'))throw new Error('Wachtzinnen komen niet overeen.');download(await encryptedBackup(s,get('password')),`zzp-boekhouding-TEST-${today}.nbbackup`);A.audit(s,'backup_downloaded','backup','Versleutelde lokale testback-up');}
 if(type==='restore'){if(!confirmed)throw new Error('Bevestig het vervangen van de testadministratie.');const file=data.get('backup') as File;if(!file?.size)throw new Error('Selecteer een back-upbestand.');const restored=await restoreBackup(new Uint8Array(await file.arrayBuffer()),get('password'));const revision=s.revision;Object.assign(s,restored);s.revision=revision;A.audit(s,'backup_restored','backup','Documenthashes en boekingsbalans gecontroleerd');}
 });});
window.addEventListener('hashchange',()=>{const hash=location.hash.slice(1);if(pages[hash]){page=hash;render();}});
function renderLogin() {
 app.innerHTML=`<main class="login-screen"><section class="panel login-panel"><div class="brand"><span>↗</span><div>ZZP<small>BOEKHOUDING</small></div></div><h1>Jouw administratie</h1><p>Log in met je Google-account om je administratie te openen.</p>${error?`<p class="error-banner" role="alert">${esc(error)}</p>`:''}${checking?'<p role="status">Google-account en toegang controleren…</p>':button('Inloggen met Google','login','','primary')+button('Opnieuw controleren','retry-auth','','text-button')}<p class="muted">Alleen een vooraf ingericht eigenaaraccount krijgt toegang.</p></section></main>`;
}
function lock() {
 authGeneration++;ownerId='';state=A.emptyState();message='';
 if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}
 renderLogin();
}
async function start() {
 lock();const generation=authGeneration;checking=true;error='';renderLogin();
 try{
  const params=new URLSearchParams(location.search);
  if(params.has('error'))throw new Error('Google-aanmelding is niet afgerond. Probeer opnieuw.');
  const identity=await verifiedIdentity();
  if(generation!==authGeneration)return;
  if(!identity){checking=false;renderLogin();return;}
  const loaded=await loadState(identity.id);validateState(loaded);
  if(generation!==authGeneration)return;
  state=loaded;ownerId=identity.id;checking=false;
  page=pages[location.hash.slice(1)]?location.hash.slice(1):'overview';
  message='Ingelogd met Google. Je eigenaarstoegang is gecontroleerd.';render();
 }catch(e){if(generation!==authGeneration)return;checking=false;error=e instanceof Error?e.message:'Toegang kon niet worden gecontroleerd.';renderLogin();}
}
supabase?.auth.onAuthStateChange((event)=>{
 if(event==='SIGNED_OUT'){checking=false;lock();}
 // Defer network verification until the SDK releases its auth lock.
 if(event==='SIGNED_IN'||event==='TOKEN_REFRESHED')setTimeout(()=>{if(!checking)void start();},0);
});
window.addEventListener('pageshow',event=>{if(event.persisted)void start();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){checking=false;lock();}else void start();});
void start();
